import {Language} from "@/types";

export const languages: Language[] = [
    { code: "auto", name: "Auto Detect", nativeName: "Автоопределение" },
    { code: "en", name: "English", nativeName: "English" },
    { code: "ru", name: "Russian", nativeName: "Русский" },
    { code: "es", name: "Spanish", nativeName: "Español" },
    { code: "fr", name: "French", nativeName: "Français" },
    { code: "de", name: "German", nativeName: "Deutsch" },
    { code: "it", name: "Italian", nativeName: "Italiano" },
    { code: "pt", name: "Portuguese", nativeName: "Português" },
    { code: "zh", name: "Chinese", nativeName: "中文" },
    { code: "ja", name: "Japanese", nativeName: "日本語" },
    { code: "ko", name: "Korean", nativeName: "한국어" },
    { code: "ar", name: "Arabic", nativeName: "العربية" },
    { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
    { code: "th", name: "Thai", nativeName: "ไทย" },
    { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
    { code: "tr", name: "Turkish", nativeName: "Türkçe" },
    { code: "pl", name: "Polish", nativeName: "Polski" },
    { code: "nl", name: "Dutch", nativeName: "Nederlands" },
    { code: "sv", name: "Swedish", nativeName: "Svenska" },
    { code: "da", name: "Danish", nativeName: "Dansk" },
    { code: "no", name: "Norwegian", nativeName: "Norsk" },
    { code: "fi", name: "Finnish", nativeName: "Suomi" },
    { code: "cs", name: "Czech", nativeName: "Čeština" },
    { code: "sk", name: "Slovak", nativeName: "Slovenčina" },
    { code: "hu", name: "Hungarian", nativeName: "Magyar" },
    { code: "ro", name: "Romanian", nativeName: "Română" },
    { code: "bg", name: "Bulgarian", nativeName: "Български" },
    { code: "hr", name: "Croatian", nativeName: "Hrvatski" },
    { code: "sr", name: "Serbian", nativeName: "Српски" },
    { code: "sl", name: "Slovenian", nativeName: "Slovenščina" },
    { code: "et", name: "Estonian", nativeName: "Eesti" },
    { code: "lv", name: "Latvian", nativeName: "Latviešu" },
    { code: "lt", name: "Lithuanian", nativeName: "Lietuvių" },
    { code: "uk", name: "Ukrainian", nativeName: "Українська" },
    { code: "be", name: "Belarusian", nativeName: "Беларуская" },
    { code: "ka", name: "Georgian", nativeName: "ქართული" },
    { code: "am", name: "Amharic", nativeName: "አማርኛ" },
    { code: "he", name: "Hebrew", nativeName: "עברית" },
    { code: "fa", name: "Persian", nativeName: "فارسی" },
    { code: "ur", name: "Urdu", nativeName: "اردو" },
    { code: "bn", name: "Bengali", nativeName: "বাংলা" },
    { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
    { code: "te", name: "Telugu", nativeName: "తెలుగు" },
    { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
    { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
    { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
    { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
    { code: "mr", name: "Marathi", nativeName: "मराठी" },
    { code: "ne", name: "Nepali", nativeName: "नेपाली" },
    { code: "si", name: "Sinhala", nativeName: "සිංහල" },
    { code: "my", name: "Myanmar", nativeName: "မြန်မာ" },
    { code: "km", name: "Khmer", nativeName: "ខ្មែរ" },
    { code: "lo", name: "Lao", nativeName: "ລາວ" },
    { code: "az", name: "Azerbaijani", nativeName: "Azərbaycan" },
    { code: "kk", name: "Kazakh", nativeName: "Қазақ" },
    { code: "ky", name: "Kyrgyz", nativeName: "Кыргыз" },
    { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
    { code: "tg", name: "Tajik", nativeName: "Тоҷикӣ" },
    { code: "mn", name: "Mongolian", nativeName: "Монгол" },
    { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
    { code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
    { code: "tl", name: "Filipino", nativeName: "Filipino" },
    { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
    { code: "zu", name: "Zulu", nativeName: "isiZulu" },
    { code: "af", name: "Afrikaans", nativeName: "Afrikaans" },
    { code: "sq", name: "Albanian", nativeName: "Shqip" },
    { code: "eu", name: "Basque", nativeName: "Euskera" },
    { code: "ca", name: "Catalan", nativeName: "Català" },
    { code: "gl", name: "Galician", nativeName: "Galego" },
    { code: "is", name: "Icelandic", nativeName: "Íslenska" },
    { code: "ga", name: "Irish", nativeName: "Gaeilge" },
    { code: "mt", name: "Maltese", nativeName: "Malti" },
    { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
]
